apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-atlantis-spot-cluster
  region: ap-southeast-1
  version: "1.21"

managedNodeGroups:
  - name: eks-atlantis-spot-cluster
    spot: true
    minSize: 1
    maxSize: 5
    volumeSize: 10
    volumeType: gp2
    volumeEncrypted: true
    instanceType: t2.medium
    instancePrefix: spot-nodes
    labels:
      lifecycle: Ec2Spot
      aws.amazon.com/spot: "true"
      nodegroup-type: spot
      node-type: spot
    tags:
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
      k8s.io/cluster-autoscaler/node-template/label/intent: apps
      k8s.io/cluster-autoscaler/node-template/label/node-type: spot
      k8s.io/cluster-autoscaler/node-template/label/nodegroup-type: spot
      nodegroup-role: worker
    availabilityZones: ["ap-southeast-1a", "ap-southeast-1b"]
    iam:
      withAddonPolicies:
        autoScaler: true
